---
admin_pass: "{{ lookup('password', 'passwords/admin.pass') }}"
demo_pass: "{{ lookup('password', 'passwords/demo.pass') }}"
mysql_root_pass: "{{ lookup('password', 'passwords/mysql_root.pass') }}"
cinderdb_pass: "{{ lookup('password', 'passwords/cinderdb.pass') }}"
cinder_pass: "{{ lookup('password', 'passwords/cinder.pass') }}"
dashdb_pass: "{{ lookup('password', 'passwords/dashdb.pass') }}"
glancedb_pass: "{{ lookup('password', 'passwords/glancedb.pass') }}"
glance_pass: "{{ lookup('password', 'passwords/glance.pass') }}"
keystonedb_pass: "{{ lookup('password', 'passwords/keystonedb.pass') }}"
keystone_pass: "{{ lookup('password', 'passwords/keystone.pass') }}"
neutrondb_pass: "{{ lookup('password', 'passwords/neutrondb.pass') }}"
neutron_pass: "{{ lookup('password', 'passwords/neutron.pass') }}"
neutron_metadata: "{{ lookup('password', 'passwords/neutron_metadata.pass') }}"
novadb_pass: "{{ lookup('password', 'passwords/novadb.pass') }}"
nova_pass: "{{ lookup('password', 'passwords/nova.pass') }}"
rabbit_pass: "{{ lookup('password', 'passwords/rabbit.pass') }}"
barbicandb_pass: "{{ lookup('password', 'passwords/barbicandb.pass') }}"
barbican_pass: "{{ lookup('password', 'passwords/barbican.pass') }}"
swiftdb_pass: "{{ lookup('password', 'passwords/swiftdb.pass') }}"
swift_pass: "{{ lookup('password', 'passwords/swift.pass') }}"
swift_hash: "{{ lookup('password', 'passwords/swift_hash.pass') }}"
heatdb_pass: "{{ lookup('password', 'passwords/heatdb.pass') }}"
heat_pass: "{{ lookup('password', 'passwords/heat.pass') }}"
heat_domain_admin_pass: "{{ lookup('password', 'passwords/heat_domain_admin.pass') }}"
